name: Build with Jekyll
description: Build Jekyll site with Python dependencies

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
      with:
        ruby-version: '3.1'
        bundler-cache: true
        cache-version: 0
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"
    - name: Install dependencies
      run: pip install -r _scripts/requirements.txt
      shell: bash
    - name: Create Calendar file
      run: python _scripts/create_calendar.py --talks_dir _data/seminar_talks/ --output_dir downloads/
      shell: bash
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Build with Jekyll
      run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production
      shell: bash
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
