# Jekyll configuration
# adapted from https://github.com/mpa139/allanlab

title: GDL Group @ Chalmers
email: your-email@example.com
description: >
  Website of the Geometric Deep Learning Group at Chalmers University of Technology and University of Gothenburg.
baseurl: ""
url: ""
remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme

include:
  - _pages

sass:
    sass_dir: _sass

collections:
  members:
    output: true
  # publications:

defaults:
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"


collections_dir: collections

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


# autoprefixer plugin for building bootstrap from source
autoprefixer:
  browsers:
    - last 4 versions

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
